name: Create file on merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-file:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create file
        run: |
           cp 1234.txt 1234_copy.txt
           echo "1234.txt file has been copied to 1234_copy.txt"
        shell: bash
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: file-copy
          path: 1234_copy.txt


